# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Skillhub
email: joshgorman@cmail.carleton.ca
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Joshua Gorman
  pic: 1
  position: Computer Science at Carleton University
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Bhalachandra Malghan
  pic: 2
  position: Computer Engineering at University of Ottawa
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Devin Sit
  pic: 3
  position: Software Engineering at University of Ottawa
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Liannus/Skillhub

# Software used inside of the application
software:
  - title: react
    url: http://twitter.com/jekyllrb
  - title: node-js
    url:
  - title: sass
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: Docker
    url: http://bitbucket.org/jekyll
  - title: GCP
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
